sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: b72o3XVEGn9YATKTZxRJgd61dCpZMgXaxUKiOMFNLj+6Wl+ff9lOUCyEOd1TP//DV6KdHPtJKg6Ryua0tzJ7h7d/DpIPWg/S0nGXr9n+Wfw9L2V+p0mEIiDH1LVD1qnEq86+gTmLjXIwtnYhiyrWhtnIo+nW/IGFsp30q9sL5GLM1U2I/tdEZ91WhXdXojUPQyVHiAGoyHzl4LFYq7jrAQJhbejvwfeJLcvbZlpx8swptvJ1L1swJ2HcwtVzE8c/2tcGcaj/D5IunEqMC9T4Ig8qW0G52AQhNipkRPoetX9f15h2n2O8WjoveTku+H6CI2t/HfMP4D51hSyHmt6VtoImeF6YwQiEaoKt8JUD/j+CM55vG2No69/xMM5WmGfXCQfabw6+e2ioQCjBDASUm6JEbiIJnqaF20AM9fW0L5grAHHRp0YTjhxfNj7c+FTq5KuU/imVlTnK613t1f7BHxtLgY27NR5/6hGTU1p0zf3gyFvlzhm1n/2MeFpDbsjuG3VHc3lxtcGm2dZIRDXSOBMibUoOa8HewQxJfZ5edIGD74GQprH41idcvJeoA9pG8mEUFf+F2KXJUew6+KO+do+00gmALgqLnjm+JGKr5hWuMWz78zDp44qIHGgIWNemEaishNvj6Xyg9f8ryuxbiYEtsSaSzeKQln7BjrD2/fs=
  - secure: vHV5IF29Rrcd9umRa87FVUBgYYBHXHvKG+pYExnWHgvGWyc1ArEGnBBfY79oZENTheqTxx8sdBWT/SwHicezbzrZlzkAbAbct2k8nS6thDM4l8MRdK/9pg0wkLi1xexfFE2jHpblOrykp3wyUUJuVgLebXSFNmSY6WJRMjL6D9Bvp72ld/ZnFOr6lHFD3SPnMMyZO8nS0gSEVPqy+qFPLgDWKLcGcJSUteYexByhq5XS8lBvPN1D0qzPPi0YIly/ovYKiaHMPpyx10V3mTFxCs5txwZXgtC2lhU44jvmWbVyryR/Q/eSwHVRqJnufr5JXehrmi/cCAJQrZ9BqmDOXWfj/hIiQMvblQ2hm6hHP3VAZHyuBUeV2Plt3UmKi9DDq9/tcGiBUNPcERPNobkuW+10FVF75HZioUbonOTNiEQl2ke1uY1D75bGygGiaozUaIHyKTp22ZQYI58F9C4m3ZZ9TR6WRR8XXfo8kUAkaFa+iS3x25jg7MoT3ZETEZ8FJfNEy5L3TdKbaVtNj/wzPj9uKcLFQMZ/MCcpEbNlRQYawYcFpvAwIHW/Eet30O/5dBVLfRPSzIosx7ZgcYc7PS9ZiRT7L3TSY+lmVF82WjsXxEdhTkwwQv7IldPvEvblNmIHCrR3VVEvor1utvNmFciJqraF69bZTXLCRkaZpFo=
branches:
  only:
  - master
