# Jykell configuration
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'IAMSTU'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# Author's info
author: 'Stu Lynch'
# edit 'categories' in the front matter of every post to match this username
nickname: Stu
bio: 'A paranormal expert and his daughter bunk in an abandoned house populated by 3 mischievous ghosts and one friendly one.'
location: 'Brighton, UK'
url: 'http://studomonly.github.io/iamstu/'
image: 'assets/images/casper.png'

short_url: 'studomonly.github.io/iamstu/'
google_analytics: UA-69281367-1
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /iamstu/

# Permalinks
permalink: /:iamstu
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

safe: false
lsi: false
username: studomonly
repo: iamstu
branch: gh-pages
relative_source: ../iamstu/
destination: ../iamstu-pages/
production_url:  https://studomonly.github.io/iamstu/
source_url:      https://github.com/studomonly/iamstu/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
